### ISSUE TITLE
Support for m3u8 urls

### ISSUE THREAD

**Issue by s1-ranjan** [zerosonesfun/flarum-inline-audio#1]
I am trying to use few m3u8 urls such as 
http://air.pc.cdn.bitgravity.com/air/live/pbaudio087/playlist.m3u8
in this plugin, but it not working, please extend your support for m3u8 urls.

**Comment by zerosonesfun** [comment]
Hello,

This won't be possible. This uses an existing JavaScript library called Soundmanager 2. The developer who makes Soundmanager 2 would have to update their library.

Closing issue since it is not possible at this time.

Thanks,
Billy
